name: 'build'

on:
  push:
    branches:
      - master
      - ci-dev
  workflow_dispatch: {}

env:
  WINSDK_VERSION: 22621

jobs:
  build-straycat:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: 
          - runs-on: windows-latest
            arch: win-x64
            os: windows
          - runs-on: windows-11-arm
            arch: win-arm64
            os: windows
          - runs-on: macos-13
            arch: osx-x64
            os: mac
          - runs-on: macos-15
            arch: osx-arm64
            os: mac
          - runs-on: ubuntu-latest
            arch: linux-x64
            os: linux
          - runs-on: ubuntu-24.04-arm
            arch: linux-arm64
            os: linux
    runs-on: ${{ matrix.os.runs-on }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        id: winsdk
        if: matrix.os.os == 'windows'
        with:
          sdk-version: ${{ env.WINSDK_VERSION }}
      
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      
      - name: Enter visual studio dev console 
        uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os.os == 'windows'

      - name: Build Straycat
        run: cargo build --release
      
      - name: Store artifacts (windows)
        if: matrix.os.os == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os.runs-on }}
          path: target/release/straycat-rs.exe
      
      - name: Store artifacts (posix)
        if: matrix.os.os != 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os.runs-on }}
          path: target/release/straycat-rs

  deploy:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    needs: [build-straycat]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Get version from Cargo.toml
        uses: thebongy/version-check@v2
        with:
          file: Cargo.toml
          tagFormat: v${version}
        id: getversion

      - name: Get checksums for build
        id: checksums
        run: |
          for arch in "win-x64" "win-arm64" "osx-x64" "osx-arm64" "linux-x64" "linux-arm64"; do
            # if windows, executable is straycat-rs.exe, otherwise straycat-rs
            if [[ $arch == "win"* ]]; then
              file="${arch}/straycat-rs.exe"
            else
              file="${arch}/straycat-rs"
            fi
            echo "${arch}_SHA1=$(shasum -a 1 "$file" | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"
            echo "${arch}_SHA256=$(shasum -a 256 "$file" | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"
            echo "${arch}_SHA384=$(shasum -a 384 "$file" | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"
            echo "${arch}_MD5=$(md5sum "$file" | awk '{ print $1 }')" >> "$GITHUB_OUTPUT"
          done

      - uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with: 
          tag: ${{ steps.getversion.outputs.releaseVersion }}

      - name: Create tag
        if: steps.check-tag.outputs.exists == 'false' 
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.getversion.outputs.releaseVersion }}',
              sha: context.sha
            })

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          make_latest: true
          files: |
            win-x64/straycat-rs.exe
            win-arm64/straycat-rs.exe
            osx-x64/straycat-rs
            osx-arm64/straycat-rs
            linux-x64/straycat-rs
            linux-arm64/straycat-rs
          name: 'straycat-rs ${{ steps.getversion.outputs.rawVersion }}'
          tag_name: '${{ steps.getversion.outputs.releaseVersion }}'
          body: |
            # straycat-rs ${{ steps.getversion.outputs.rawVersion }}

            A stable build of straycat-rs.

            ## [${{ steps.getversion.outputs.rawVersion }}] - xxxx-xx-xx

            ### Added

            ### Changed

            ### Fixed

            ### Hashes
            #### Windows x64
            | Hash function | Hash |
            | --- | --- |
            | MD5 | `${{ steps.checksums.outputs.win-x64_MD5 }}` |
            | SHA1 | `${{ steps.checksums.outputs.win-x64_SHA1 }}` |
            | SHA256 | `${{ steps.checksums.outputs.win-x64_SHA256 }}` |
            | SHA384 | `${{ steps.checksums.outputs.win-x64_SHA384 }}` |

            #### Windows arm64
            | Hash function | Hash |
            | --- | --- |
            | MD5 | `${{ steps.checksums.outputs.win-arm64_MD5 }}` |
            | SHA1 | `${{ steps.checksums.outputs.win-arm64_SHA1 }}` |
            | SHA256 | `${{ steps.checksums.outputs.win-arm64_SHA256 }}` |
            | SHA384 | `${{ steps.checksums.outputs.win-arm64_SHA384 }}` |

            #### MacOS x64
            | Hash function | Hash |
            | --- | --- |
            | MD5 | `${{ steps.checksums.outputs.osx-x64_MD5 }}` |
            | SHA1 | `${{ steps.checksums.outputs.osx-x64_SHA1 }}` |
            | SHA256 | `${{ steps.checksums.outputs.osx-x64_SHA256 }}` |
            | SHA384 | `${{ steps.checksums.outputs.osx-x64_SHA384 }}` |

            #### MacOS arm64
            | Hash function | Hash |
            | --- | --- |
            | MD5 | `${{ steps.checksums.outputs.osx-arm64_MD5 }}` |
            | SHA1 | `${{ steps.checksums.outputs.osx-arm64_SHA1 }}` |
            | SHA256 | `${{ steps.checksums.outputs.osx-arm64_SHA256 }}` |
            | SHA384 | `${{ steps.checksums.outputs.osx-arm64_SHA384 }}` |

            #### Linux x64
            | Hash function | Hash |
            | --- | --- |
            | MD5 | `${{ steps.checksums.outputs.linux-x64_MD5 }}` |
            | SHA1 | `${{ steps.checksums.outputs.linux-x64_SHA1 }}` |
            | SHA256 | `${{ steps.checksums.outputs.linux-x64_SHA256 }}` |
            | SHA384 | `${{ steps.checksums.outputs.linux-x64_SHA384 }}` |

            #### Linux arm64
            | Hash function | Hash |
            | --- | --- |
            | MD5 | `${{ steps.checksums.outputs.linux-arm64_MD5 }}` |
            | SHA1 | `${{ steps.checksums.outputs.linux-arm64_SHA1 }}` |
            | SHA256 | `${{ steps.checksums.outputs.linux-arm64_SHA256 }}` |
            | SHA384 | `${{ steps.checksums.outputs.linux-arm64_SHA384 }}` |

            **Full Changelog**: https://github.com/UtaUtaUtau/straycat-rs/blob/main/CHANGELOG.md
          generate_release_notes: true
